### ISSUE TITLE
Add "symfony/yaml" as requirement

### ISSUE THREAD

**Issue by asokol-teq** [AuthorizeNet/sdk-php#154]
As it describes jms/serializer/composer.json:
```
"suggest": {
        "symfony/yaml": "Required if you'd like to serialize data to YAML format."
 },
```
So before I add "symfony/yaml": "3.1.1" to "require" section of own composer.json, 
I got the following error:

```
<pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Class &#039;Symfony\Component\Yaml\Yaml&#039; not found&#039; 

in /vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/YamlDriver.php:35

Stack trace:
#0 /vendor/jms/metadata/src/Metadata/Driver/DriverChain.php(38): Metadata\Driver\AbstractFileDriver-&gt;loadMetadataForClass()
#1 /vendor/jms/metadata/src/Metadata/MetadataFactory.php(103): Metadata\Driver\DriverChain-&gt;loadMetadataForClass()
#2 /vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(188): Metadata\MetadataFactory-&gt;getMetadataForClass()
#3/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(176): JMS\Serializer\GraphNavigator-&gt;accept()
#4 /vendor/jms/serializer/src/JMS/Serializer/Serializer.php(82): JMS\Serializer\Serializer-&gt;visit()
#5 /vendor/phpoption/phpoption/src/PhpOption/Some.php(89): JMS\Serializer\Serializer-&gt;JMS\Serializer\{closure}()
#6 /vendor/phpoption/phpoption/src/PhpOption/Some.php(89): ::call_user_func:{/vendor/phpoption/phpoption/src/PhpOption/Some.php:89}()
#7 /vendor/jms/serializer/src/JMS/Serializer/Serializer.php(85): PhpOption\Some-&gt;map()
#8 /vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php(114): JMS\Serializer\Serializer-&gt;serialize()
#9 /vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php(104): net\authorize\api\controller\base\ApiOperationBase-&gt;execute()
```

Looks like it worth to add  "symfony/yaml" as requirement to composer.json and README.
Tnx

**Comment by texdc** [comment]
@ramittal added [the dependency](https://github.com/AuthorizeNet/sdk-php/blame/master/lib/net/authorize/api/controller/base/ApiOperationBase.php#L75)

A simple PR will fix this. You can add the require to your project's `composer.json` in the mean time.

**Comment by jdpace2** [comment]
This fix prevents installing the library with composer with the following error: "authorizenet/authorizenet 1.9.0 requires jms/serializer serializer-master-dev as 1.0 -> no matching package found."
